#!/bin/bash

SCRIPTPATH=$(dirname $(readlink -f $0))
cd $SCRIPTPATH
pythonpath=/$HOME/.pyenv/versions/3.12.8/bin

if [ ! -d venv ]; then
    $pythonpath/python3 -m venv venv
fi
source venv/bin/activate
$pythonpath/pip3 install -r requirements.txt

$pythonpath/python3 main.py