#!/bin/bash

SCRIPTPATH=$(dirname $(readlink -f $0))
cd $SCRIPTPATH

if [ ! -d venv ]; then
    python3 -m venv venv
    source venv/bin/activate
    pip3 install -r requirements.txt
else
    source venv/bin/activate
fi

python3 main.py